/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.example.demo.View.ViPham;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author TOAN
 */
public class XuLyViPham extends javax.swing.JPanel {
	private Color mainColor = Color.decode("#dff9fb");
	private Font sgUI18b = new Font("Segoe UI", Font.BOLD, 18);
    /** Creates new form Xulyvipham1 */
    public XuLyViPham() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        txtThongTin2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbTimKiem2 = new javax.swing.JComboBox<>();
        btnXoa2 = new javax.swing.JButton();
        btnLamMoi2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnTimKiem2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();
        btnThem3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        label1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label1.setText("Xử Lý Vi Phạm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtThongTin2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtThongTin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThongTin2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nhập thông tin tìm kiếm");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Tìm kiếm theo:");

        cbbTimKiem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã xử lý", "Mã thành viên", "Hình thức xử lý", "Số tiền", "Ngày xử lý", "Trạng thái" }));
        cbbTimKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimKiem2ActionPerformed(evt);
            }
        });

        btnXoa2.setBackground(new java.awt.Color(126, 214, 223));
        btnXoa2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa2.setForeground(new java.awt.Color(204, 0, 0));
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/delete button.png"))); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.setBorderPainted(false);
        btnXoa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa2.setFocusPainted(false);

        btnLamMoi2.setBackground(new java.awt.Color(126, 214, 223));
        btnLamMoi2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLamMoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/Refresh_icon.png"))); // NOI18N
        btnLamMoi2.setBorderPainted(false);
        btnLamMoi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi2.setFocusPainted(false);
        btnLamMoi2.setLabel("Refresh");

        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1),  new Integer(1), "Khóa Thẻ",  new Integer(2000000), "03/09/2003",  new Integer(0)},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã xử lý", "Mã thành viên", "Hình thức xử lý", "Số tiền", "Ngày xử lý", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(40);
        jScrollPane3.setViewportView(jTable3);

        btnTimKiem2.setBackground(new java.awt.Color(126, 214, 223));
        btnTimKiem2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/search icon.png"))); // NOI18N
        btnTimKiem2.setText("Tìm Kiếm");
        btnTimKiem2.setBorderPainted(false);
        btnTimKiem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem2.setFocusPainted(false);

        btnSua2.setBackground(new java.awt.Color(126, 214, 223));
        btnSua2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua2.setForeground(new java.awt.Color(0, 0, 153));
        btnSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/buttonDetails.png"))); // NOI18N
        btnSua2.setText("Sửa");
        btnSua2.setBorderPainted(false);
        btnSua2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua2.setFocusPainted(false);
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSua2ActionPerformed(evt);
            }
        });

        btnThem2.setBackground(new java.awt.Color(126, 214, 223));
        btnThem2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(0, 153, 51));
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/add button.png"))); // NOI18N
        btnThem2.setText("Thêm");
        btnThem2.setBorderPainted(false);
        btnThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem2.setFocusPainted(false);
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnThem2ActionPerformed(evt);
            }
        });

        btnThem3.setBackground(new java.awt.Color(126, 214, 223));
        btnThem3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem3.setForeground(new java.awt.Color(0, 153, 51));
        btnThem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/example/demo/View/images/add button.png"))); // NOI18N
        btnThem3.setText("Xử Lý");
        btnThem3.setBorderPainted(false);
        btnThem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem3.setFocusPainted(false);
        btnThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThem3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(cbbTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(735, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtThongTin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLamMoi2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(cbbTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(457, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtThongTin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongTin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThongTin2ActionPerformed

    private void cbbTimKiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimKiem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTimKiem2ActionPerformed

//    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
//        java.awt.Frame parentFrame = new java.awt.Frame(); // Khởi tạo một đối tượng Frame
//        boolean isModal = true; // Xác định xem JDialog có là modal hay không
//
//        ThemXuLy themXyLyDialog = new ThemXuLy(parentFrame, isModal); // Khởi tạo đối tượng ThemXyLy
//        themXuLyDialog.setLocationRelativeTo(null); // Đặt JDialog ra giữa màn hình
//        themXuLyDialog.setVisible(true); // Hiển thị JDialog
//    }//GEN-LAST:event_btnThem2ActionPerformed

//    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
//        // TODO add your handling code here:
//        java.awt.Frame parentFrame = new java.awt.Frame(); // Khởi tạo một đối tượng Frame
//        boolean isModal = true; // Xác định xem JDialog có là modal hay không
//
//        SuaXuLy suaXuLyDialog = new SuaXuLy(parentFrame, isModal); // Khởi tạo đối tượng ThemXyLy
//        suaXuLyDialog.setLocationRelativeTo(null); // Đặt JDialog ra giữa màn hình
//        suaXuLyDialog.setVisible(true); // Hiển thị JDialog
//    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi2;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnThem3;
    private javax.swing.JButton btnTimKiem2;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JComboBox<String> cbbTimKiem2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private java.awt.Label label1;
    private javax.swing.JTextField txtThongTin2;
    // End of variables declaration//GEN-END:variables

}
